BanksySan.Learning.ClrMD.Web/Models/ProbeInfo.cs
namespace BanksySan.Learning.ClrMD.Web.Models
{
    using System;
    using System.Collections.Generic;

    public class ProbeInfo
    {
        public ProbeInfo(IEnumerable<SegmentInfo> segments, DateTime time)
        {
            Segments = segments;
            Time = time;
        }

        public IEnumerable<SegmentInfo> Segments { get; }
        public DateTime Time { get; }
    }
}

BanksySan.Learning.ClrMD.Web/Models/RunInfo.cs
namespace BanksySan.Learning.ClrMD.Web.Models
{
    using System;
    using System.Collections.Generic;

    public class RunInfo
    {
        public RunInfo(IEnumerable<ProbeInfo> probes, DateTime dateTime)
        {
            Probes = probes;
            DateTime = dateTime;
        }

        public IEnumerable<ProbeInfo> Probes { get; }
        public DateTime DateTime { get; }
    }
}

BanksySan.Learning.ClrMD.Web/Models/RunSummary.cs
namespace BanksySan.Learning.ClrMD.Web.Models
{
    using System;

    public class RunSummary
    {
        public RunSummary(DateTime dateTime, Guid runId)
        {
            DateTime = dateTime;
            RunId = runId;
        }

        public DateTime DateTime { get; }
        public Guid RunId { get; }
    }
}

BanksySan.Learning.ClrMD.Web/Models/SegmentInfo.cs
namespace BanksySan.Learning.ClrMD.Web.Models
{
    public class SegmentInfo
    {
        /// <inheritdoc />
        public SegmentInfo(ulong startAddress, ulong length, ulong commitedEnd, bool ephemaral, bool large,
                           ulong reservedEnd)
        {
            StartAddress = startAddress;
            Length = length;
            CommitedEnd = commitedEnd;
            Ephemaral = ephemaral;
            Large = large;
            ReservedEnd = reservedEnd;
        }

        public ulong StartAddress { get; }
        public ulong Length { get; }
        public ulong CommitedEnd { get; }
        public bool Ephemaral { get; }
        public bool Large { get; }
        public ulong ReservedEnd { get; }
    }
}

BanksySan.Learning.ClrMD.Web/Controllers/HomeController.cs
namespace BanksySan.Learning.ClrMD.Web.Controllers
{
    using Data;
    using Microsoft.AspNetCore.Mvc;

    public class HomeController : Controller
    {
        private static readonly GetRuns GET_RUNS = new GetRuns();

        public IActionResult Index()
        {
            var runs = GET_RUNS.Execute();

            return View(runs);
        }
    }
}

BanksySan.Learning.ClrMD.Web/Controllers/RunsController.cs
namespace BanksySan.Learning.ClrMD.Web.Controllers
{
    using System;
    using Microsoft.AspNetCore.Mvc;
    using Data;

    public class RunsController : Controller
    {
        private static readonly GetRunDetail GET_RUN_DETAIL = new GetRunDetail();

        public IActionResult Index(Guid id)
        {
            var runDetail = GET_RUN_DETAIL.Execute(id);

            return View(runDetail);
        }
    }
}

BanksySan.Learning.ClrMD.Web/Views/Home/Index.cshtml
@model IEnumerable<BanksySan.Learning.ClrMD.Web.Models.RunSummary>
@{
    ViewData["Title"] = "Dave's Metrics";
}

<table class="table table-hover">
    <thead>
    <tr>
        <th>Run ID</th>
        <th>Time</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var run in Model)
    {
        <tr>
            <td style="margin: 10px 10px 2px; padding: 10px 10px 2px">
                <samp>@Html.ActionLink(run.RunId.ToString("B"), "Index", "Runs", new {Id = run.RunId})</samp>
            </td>
            <td>
                <samp>@run.DateTime.ToString("g")</samp>
            </td>
        </tr>
    }
    </tbody>
</table>

BanksySan.Learning.ClrMD.Web/Views/Runs/Index.cshtml
@model BanksySan.Learning.ClrMD.Web.Models.RunInfo
@{
    ViewData["Title"] = "Run Detail";
}

<h2>@ViewData["Title"]</h2>

<p>@Model.DateTime</p>

<p>Probes:</p>
@foreach (var probe in Model.Probes.OrderBy(x => x.Time))
{
    <ol>
        <li>@probe.Time, @probe.Segments.Count()</li>
    </ol>
}

BanksySan.Learning.ClrMD.Web/Views/Shared/Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BanksySan.Learning.ClrMD.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">BanksySan.Learning.ClrMD.Web</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2016 - BanksySan.Learning.ClrMD.Web</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

BanksySan.Learning.ClrMD.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BanksySan.Learning.ClrMD.Web</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css"/>
        <link rel="stylesheet" href="~/css/site.css"/>
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"/>
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true"/>
    </environment>

</head>
<body>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; 2017 - BanksySan.Learning.ClrMD.Web</p>
    </footer>
</div>

<environment names="Development">
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</environment>
<environment names="Staging,Production">
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
    </script>
    <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
            asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
            asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
            crossorigin="anonymous"
            integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
    </script>
    <script src="~/js/site.min.js" asp-append-version="true"></script>
</environment>

@RenderSection("Scripts", false)
</body>
</html>